server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seconds_kill?serverTimezone=GMT%2B8
    username: root
    password: yaoyao0203
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxWait: 60000
    minIdle: 1 #最小连接池数量
    maxActive: 50 #最大连接池数量
    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache，对支持游戏的数据库提升大，mysql建议关闭
    maxOpenPreparedStatements: -1 #要启用PSCache，配置必须大于0
    validationQuery: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效(建议配置为true，不影响性能，并且保证安全性)
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    # 默认超时2000ms
    timeout: 5000
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
# xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-type: MYSQL
configuration:
  map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#logging:
#  level:
#    com.fuqiang.secondskill.mapper: debug
